apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-block-pvc
  namespace: default
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
